### ISSUE TITLE
Method to return all possible detected object types

### ISSUE THREAD

**Issue by jimboca** [camect/camect-py#5]
@chao-camect would this be possible? Please add an API method to return a list of all possible detected object types so we know what may be seen.

**Comment by jimboca** [comment]
@chao-camect now that this is added the the firmeware, can you add it to the API?

**Comment by chao-camect** [comment]
The get_info is already returning the object list. There is not need to update this repo for this.
Can you check whether you get the object list now?

**Comment by jimboca** [comment]
Oh, awesome, didn't even look at get_info, I will take a look.

**Comment by jimboca** [comment]
Yes, I see object_name in get_info.
